doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'App\Project\Tasks\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Project/Tasks/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Project\Shared\SharedBoundedContext\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Project/Shared/SharedBoundedContext/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Project\Projections\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Project/Projections/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Project\Projects\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Project/Projects/Infrastructure/Persistence/Doctrine/Migrations'

    enable_profiler: '%kernel.debug%'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 512
            executed_at_column_name: 'executed_at'
    all_or_nothing: true
    custom_template: '%kernel.project_dir%/templates/Doctrine/migration.tpl'
