framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                middleware:
                    # each time a message is handled, the Doctrine connection
                    # is "pinged" and reconnected if it's closed. Useful
                    # if your workers run for a long time and the database
                    # connection is sometimes lost
                    - doctrine_ping_connection

                    # After handling, the Doctrine connection is closed,
                    # which can free up database connections in a worker,
                    # instead of keeping them open forever
                    - doctrine_close_connection

                    # wraps all handlers in a single Doctrine transaction
                    # handlers do not need to call flush() and an error
                    # in any handler will cause a rollback
                    #- doctrine_transaction
                    - doctrine_transaction

                    # or pass a different entity manager to any
                    #- doctrine_transaction: ['custom']
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: high
                    queues:
                        messages_high: ~
                # default configuration
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 5000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: low
                    queues:
                        messages_low: ~
                # default configuration
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 5000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
            sync: 'sync://'
            # Uncomment the following line to enable a transport named "amqp"
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\General\Infrastructure\Message\Interfaces\MessageHighInterface: async_priority_high
            App\General\Infrastructure\Message\Interfaces\MessageLowInterface: async_priority_low
            App\Project\Shared\Domain\Event\DomainEvent: async_priority_high
            App\Project\Shared\Application\Bus\Command\CommandInterface: sync
            App\Project\Shared\Application\Bus\Query\QueryInterface: sync
            # Route your messages to the transports
            # 'App\General\Infrastructure\Message\YourMessage': async

when@test:
    framework:
        messenger:
            transports:
                async_priority_high: 'in-memory://'
                async_priority_low: 'in-memory://'
